kind: pipeline
name: default

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile

  - name: bootstrap
    image: node:current-alpine
    commands:
      - yarn bootstrap

  - name: lint
    image: node:current-alpine
    commands:
      - yarn command lint

  - name: build
    image: node:current-alpine
    commands:
      - PACKAGE="@cenk1cenk2/boilerplate-oclif" yarn command build

  - name: publish
    image: node:current-alpine
    commands:
      - PACKAGE="@cenk1cenk2/boilerplate-oclif" yarn release
    environment:
      GH_TOKEN:
        from_secret: GITHUB_TOKEN
