version: "3.7"
services:
  monorepo:
    image: cenk1cenk2/lerna-dev:latest
    environment:
      - SERVICES=packages/cli:packages/common
      - RUN_IN_BAND=packages/common
    volumes:
      - .:/data/app
