name: Renovate
on:
  schedule:
    - cron: '0/15 * * * *'
  workflow_dispatch:
    
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Renovate Repository
        uses: renovatebot/github-action@v21.30.0
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
